name: run_update_feed

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#40_9_*_*_0
    - cron: '0 05 * * 1-5' # runs at 05:00 UTC every weekday
    - cron: '40 9 * * 0' # tests 09:40 on sunday

jobs:
  UpdateFeed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install reqs
        run: pip install -r requirements.txt         

      - name: Run script
        shell: bash
        run: python queries_to_feeds.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update the feed(s) from the Action'
